connections {
    host-c-to-host-d {
        version = 2

        local_addrs = 10.20.1.10
        remote_addrs = 10.20.1.20

        local {
            auth = psk
            id = host-c
        }

        remote {
            auth = psk
            id = host-d
        }

        children {
            host-c-to-host-d {
                mode = transport
                local_ts = 10.20.1.10/32
                remote_ts = 10.20.1.20/32

                esp_proposals = aes256gcm16-modp2048

                start_action = trap
            }
        }

        proposals = aes256-sha256-modp2048
    }
}
