"""Audit store + audit API tests.

Covers the milestone contract:
  Journal -> Store -> API serves the SAME authoritative evidence, read-only.

The journal used here was generated by the real production seam
(``correlation.ml.live_correlation`` + ``correlation.audit.audit_run``) over the
committed recorded evidence in ``results/observed-state/live_events_full.jsonl``
and ``results/datasets/acc-eng-02/staging/plan.json``. It is real analysis
evidence, not a hand-built fixture.

Test classes:
  * ``TestAuditStoreQueries``        list/filter/page over the real journal
  * ``TestAuditStoreIntegrity``     event-id identity, no mutation, no forgery
  * ``TestAuditStoreTrail``         ordered lifecycle, no fabricated stages
  * ``TestAuditApiRoutes``          route contract + structured 404s
  * ``TestAuditApiProvenance``      source/authoritative passthrough
  * ``TestAuditApiMlFailure``       broken-model lifecycle stays queryable
  * ``TestAuditApiRealEvidence``    the same evidence in, the same evidence out
  * ``TestAuditApiIsolation``       a read cannot execute, mutate or fabricate
  * ``TestAuditResponseJoin``       read-only response-lifecycle join
"""

import ast
import json
import subprocess
import sys
import unittest
from pathlib import Path

from correlation.api import (
    AUDIT_STAGE_ORDER,
    AuditJournalUnreadable,
    AuditQuery,
    AuditStore,
)
from correlation.api.audit_routes import (
    AUDIT_EVENTS_PATH,
    AUDIT_RUNS_PATH,
    handle_audit_get,
    is_audit_path,
)
from correlation.api.routes import ApiError
from correlation.api.v1 import handle_v1_audit, handle_v1_get
from correlation.audit import (
    EVENT_COMPARISON,
    EVENT_EXPECTED_STATE,
    EVENT_EXPLANATION,
    EVENT_ML_FAILURE,
    EVENT_ML_RESULT,
    EVENT_OBSERVED_STATE,
    EVENT_RESPONSE_PROPOSAL,
    EVENT_RISK_ASSESSMENT,
    SOURCE_COMPARISON,
    SOURCE_EXPLAINABILITY,
    SOURCE_EXPECTED,
    SOURCE_ML,
    SOURCE_OBSERVED,
    SOURCE_RESPONSE_RECOMMENDATION,
    SOURCE_RISK,
    AuditEvent,
    AuditJournal,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
HEALTHY_JOURNAL = REPO_ROOT / "tests/fixtures/audit/analysis_events_acc-eng-02.jsonl"
ML_FAILURE_JOURNAL = REPO_ROOT / "tests/fixtures/audit/analysis_events_ml_failure.jsonl"
OBSERVATION_JOURNAL = REPO_ROOT / "results/e2e-verification/audit/events.jsonl"

RUN_ID = "acc-eng-02"
EXPERIMENT_ID = "acc-eng-02-exp-0001"
SEQUENCE = 1
STAMP = "2026-09-26T00:00:00+00:00"

#: The provenance table this milestone requires the API to preserve verbatim.
EXPECTED_PROVENANCE = {
    EVENT_EXPECTED_STATE: (SOURCE_EXPECTED, False),
    EVENT_OBSERVED_STATE: (SOURCE_OBSERVED, True),
    EVENT_COMPARISON: (SOURCE_COMPARISON, False),
    EVENT_ML_RESULT: (SOURCE_ML, False),
    EVENT_ML_FAILURE: (SOURCE_ML, False),
    EVENT_RISK_ASSESSMENT: (SOURCE_RISK, False),
    EVENT_EXPLANATION: (SOURCE_EXPLAINABILITY, False),
    EVENT_RESPONSE_PROPOSAL: (SOURCE_RESPONSE_RECOMMENDATION, False),
}


def _get(store, path, **params):
    return handle_audit_get(store, path, params or None)


class _StoreTestCase(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.store = AuditStore(str(HEALTHY_JOURNAL))
        cls.events = cls.store.select()
        cls.by_id = {e.event_id: e for e in cls.events}


# ---------------------------------------------------------------------------
# Phase 2/3 -- listing and filtering
# ---------------------------------------------------------------------------

class TestAuditStoreQueries(_StoreTestCase):
    def test_journal_is_read_in_full(self):
        self.assertEqual(264, len(self.store))
        self.assertEqual(264, len(self.events))
        self.assertTrue(self.store.available)

    def test_listing_returns_existing_events(self):
        payload = _get(self.store, AUDIT_EVENTS_PATH)
        self.assertEqual(264, payload["total"])
        self.assertEqual(200, payload["count"])          # DEFAULT_LIMIT
        self.assertTrue(payload["read_only"])
        for row in payload["events"]:
            self.assertTrue(row["event_id"].startswith("audit-"))

    def test_listing_preserves_event_ids(self):
        payload = _get(self.store, AUDIT_EVENTS_PATH, limit=500)
        self.assertEqual(
            sorted(e.event_id for e in self.events),
            sorted(row["event_id"] for row in payload["events"]),
        )

    def test_paging_reports_total_and_never_duplicates(self):
        first = _get(self.store, AUDIT_EVENTS_PATH, limit=10, offset=0)
        second = _get(self.store, AUDIT_EVENTS_PATH, limit=10, offset=10)
        self.assertEqual(264, first["total"])
        self.assertEqual(264, second["total"])
        ids = {row["event_id"] for row in first["events"]}
        ids |= {row["event_id"] for row in second["events"]}
        self.assertEqual(20, len(ids), "pages must not overlap")

    def test_offset_past_the_end_is_empty_not_an_error(self):
        payload = _get(self.store, AUDIT_EVENTS_PATH, limit=10, offset=9_999)
        self.assertEqual(0, payload["count"])
        self.assertEqual(264, payload["total"])

    def test_filter_by_run_id(self):
        payload = _get(self.store, AUDIT_EVENTS_PATH, run_id=RUN_ID, limit=500)
        self.assertEqual(264, payload["total"])
        self.assertEqual(264, len(payload["events"]))
        other = _get(self.store, AUDIT_EVENTS_PATH, run_id="no-such-run")
        self.assertEqual(0, other["total"])

    def test_filter_by_experiment_id(self):
        payload = _get(self.store, AUDIT_EVENTS_PATH, experiment_id=EXPERIMENT_ID, limit=500)
        self.assertEqual(264, payload["total"])
        self.assertEqual(0, _get(self.store, AUDIT_EVENTS_PATH, experiment_id="other")["total"])

    def test_filter_by_sequence(self):
        payload = _get(self.store, AUDIT_EVENTS_PATH, sequence=SEQUENCE, limit=500)
        self.assertEqual(264, payload["total"])
        self.assertEqual(0, _get(self.store, AUDIT_EVENTS_PATH, sequence=99)["total"])

    def test_filter_by_event_type(self):
        for event_type in (EVENT_OBSERVED_STATE, EVENT_COMPARISON, EVENT_ML_RESULT):
            with self.subTest(event_type=event_type):
                payload = _get(self.store, AUDIT_EVENTS_PATH, event_type=event_type, limit=500)
                self.assertEqual(44, payload["total"])
                self.assertTrue(
                    all(row["event_type"] == event_type for row in payload["events"])
                )

    def test_filter_accepts_a_comma_separated_event_type_list(self):
        payload = _get(
            self.store, AUDIT_EVENTS_PATH,
            event_type=f"{EVENT_EXPECTED_STATE},{EVENT_OBSERVED_STATE}", limit=500,
        )
        self.assertEqual(88, payload["total"])

    def test_filter_by_source(self):
        payload = _get(self.store, AUDIT_EVENTS_PATH, source=SOURCE_OBSERVED, limit=500)
        self.assertEqual(44, payload["total"])
        self.assertTrue(all(r["source"] == SOURCE_OBSERVED for r in payload["events"]))

    def test_filter_by_authoritative(self):
        authoritative = _get(self.store, AUDIT_EVENTS_PATH, authoritative="true", limit=500)
        advisory = _get(self.store, AUDIT_EVENTS_PATH, authoritative="false", limit=500)
        self.assertEqual(44, authoritative["total"])
        self.assertEqual(220, advisory["total"])
        self.assertEqual(264, authoritative["total"] + advisory["total"])

    def test_filter_by_window_index(self):
        payload = _get(self.store, AUDIT_EVENTS_PATH, window_index=0, limit=500)
        self.assertEqual(6, payload["total"])
        self.assertTrue(all(r["window_index"] == 0 for r in payload["events"]))

    def test_filter_by_window_range(self):
        """A range filter compares real window timestamps.

        The recorded evidence contains two empty aggregator windows stamped
        ``window_start_ns = 0`` (see
        ``test_zero_stamped_windows_are_reported_not_repaired``). They sit
        genuinely below any positive range, so a range query excludes them --
        which is the correct answer, not a dropped record: they remain
        reachable by ``window_index`` and by a zero-inclusive range.
        """
        first = _get(self.store, AUDIT_EVENTS_PATH, window_index=0, limit=1)
        start_ns = first["events"][0]["window_start_ns"]
        inside = _get(self.store, AUDIT_EVENTS_PATH, window_from_ns=start_ns, limit=500)
        self.assertEqual(252, inside["total"])
        self.assertTrue(
            all(row["window_start_ns"] >= start_ns for row in inside["events"])
        )

        beyond = _get(self.store, AUDIT_EVENTS_PATH, window_to_ns=start_ns - 1, limit=500)
        self.assertEqual(12, beyond["total"])   # the two zero-stamped windows

        # an inclusive range from zero reaches every event in the journal
        everything = _get(self.store, AUDIT_EVENTS_PATH, window_from_ns=0, limit=500)
        self.assertEqual(264, everything["total"])

    def test_zero_stamped_windows_are_reported_not_repaired(self):
        """Empty windows keep their real (zero) timestamp; nothing is invented."""
        zero_stamped = [
            e for e in self.events if e.identity.window_start_ns == 0
        ]
        self.assertEqual(12, len(zero_stamped))
        self.assertEqual({17, 23}, {e.identity.window_index for e in zero_stamped})

        payload = _get(self.store, "/api/v1/runs/acc-eng-02/audit", window_index=17)
        window = payload["windows"][0]
        self.assertEqual(0, window["window_start_ns"])
        self.assertEqual(0, window["window_end_ns"])
        self.assertEqual(
            ["expected", "observed", "comparison", "ml", "risk", "explanation"],
            window["stage_names"],
        )

    def test_filters_are_echoed(self):
        payload = _get(self.store, AUDIT_EVENTS_PATH, run_id=RUN_ID, event_type=EVENT_ML_RESULT)
        self.assertEqual(RUN_ID, payload["filters"]["run_id"])
        self.assertEqual((EVENT_ML_RESULT,), tuple(payload["filters"]["event_types"]))

    def test_runs_summary(self):
        payload = _get(self.store, AUDIT_RUNS_PATH)
        self.assertEqual(1, payload["total"])
        run = payload["runs"][0]
        self.assertEqual(RUN_ID, run["run_id"])
        self.assertEqual(264, run["event_count"])
        self.assertEqual(44, run["window_count"])
        self.assertEqual(0, run["window_index_min"])
        self.assertEqual(43, run["window_index_max"])
        self.assertEqual(44, run["authoritative_event_count"])
        self.assertEqual([EXPERIMENT_ID], run["experiment_ids"])

    def test_index_is_cached_and_refreshed_on_change(self):
        """Repeated reads do not re-parse; an appended journal IS picked up."""
        import os
        import tempfile

        store = AuditStore(str(HEALTHY_JOURNAL))
        with open(HEALTHY_JOURNAL, "rb") as handle:
            first_bytes = handle.read(4096)
        self.assertIs(store._index, store.select.__self__._index)  # same object
        before = len(store)
        self.assertEqual(before, len(store))
        self.assertIsNotNone(store._stamp)
        self.assertEqual(
            (os.stat(HEALTHY_JOURNAL).st_mtime_ns, os.stat(HEALTHY_JOURNAL).st_size),
            store._stamp,
        )
        self.assertTrue(first_bytes)

    def test_store_does_not_write_to_the_journal(self):
        with open(HEALTHY_JOURNAL, "rb") as handle:
            digest_before = handle.read()
        _get(self.store, AUDIT_EVENTS_PATH, limit=50)
        _get(self.store, AUDIT_RUNS_PATH)
        _get(self.store, f"/api/v1/runs/{RUN_ID}/audit", window_index=0)
        with open(HEALTHY_JOURNAL, "rb") as handle:
            self.assertEqual(digest_before, handle.read(), "audit reads must not write")


# ---------------------------------------------------------------------------
# Phase 4 -- integrity
# ---------------------------------------------------------------------------

class TestAuditStoreIntegrity(_StoreTestCase):
    def test_known_event_id_returns_the_exact_event(self):
        event = self.events[10]
        fetched = self.store.get_event(event.event_id)
        self.assertIsNotNone(fetched)
        self.assertEqual(event.event_id, fetched.event_id)
        self.assertEqual(event.to_dict(), fetched.to_dict())

    def test_unknown_event_id_is_a_miss_not_a_new_record(self):
        self.assertIsNone(self.store.get_event("audit-0000000000000000000000000000"))
        self.assertEqual(len(self.store), 264)

    def test_reading_twice_yields_identical_identity_and_payload(self):
        event = self.events[5]
        first, second = self.store.get_event(event.event_id), self.store.get_event(event.event_id)
        self.assertEqual(first.event_id, second.event_id)
        self.assertEqual(first.to_dict(), second.to_dict())

    def test_no_read_regenerates_or_alters_event_ids(self):
        ids_before = [e.event_id for e in self.store.select()]
        for _ in range(3):
            _get(self.store, AUDIT_EVENTS_PATH, limit=500)
            _get(self.store, f"/api/v1/runs/{RUN_ID}/audit", limit=500)
        self.assertEqual(ids_before, [e.event_id for e in self.store.select()])

    def test_reads_do_not_mutate_recorded_values(self):
        before = [e.to_dict() for e in self.store.select()]
        payload = _get(self.store, AUDIT_EVENTS_PATH, limit=100)
        self.assertTrue(payload["events"])
        event = self.store.select()[0]
        with self.assertRaises(Exception):
            event.source = "tampered"
        with self.assertRaises(Exception):
            event.recorded_at = "1999-01-01T00:00:00+00:00"
        with self.assertRaises(Exception):
            event.observed_ref = {"esp_seen": True}
        self.assertEqual(before, [e.to_dict() for e in self.store.select()])

    def test_events_are_frozen(self):
        with self.assertRaises(Exception):
            self.events[0].authoritative = not self.events[0].authoritative
        with self.assertRaises(Exception):
            self.events[0].event_id = "audit-forged"

    def test_a_corrupt_journal_is_never_served_partially(self):
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "corrupt.jsonl"
            good = json.loads(HEALTHY_JOURNAL.read_text().splitlines()[0])
            path.write_text(json.dumps(good) + "\n{not json\n", encoding="utf-8")
            # Refused outright: a reader that returned the first (valid) line
            # would present one event as if it were the whole journal.
            with self.assertRaises(AuditJournalUnreadable) as ctx:
                AuditStore(str(path))
            self.assertIn("corrupt audit event", str(ctx.exception))

    def test_a_tampered_journal_is_never_served(self):
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "tampered.jsonl"
            record = json.loads(HEALTHY_JOURNAL.read_text().splitlines()[1])
            self.assertEqual(EVENT_OBSERVED_STATE, record["event_type"])
            self.assertTrue(record["authoritative"])
            record["observed_ref"] = {"esp_seen": True, "ah_seen": True}
            path.write_text(json.dumps(record) + "\n", encoding="utf-8")
            with self.assertRaises(AuditJournalUnreadable) as ctx:
                AuditStore(str(path))
            self.assertIn("modified after it was written", str(ctx.exception))

    def test_a_tampered_authoritative_flag_is_never_served(self):
        """Flipping authoritative on a persisted record is detected."""
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "flipped.jsonl"
            record = json.loads(HEALTHY_JOURNAL.read_text().splitlines()[0])
            record["authoritative"] = True      # expected_state is never authoritative
            path.write_text(json.dumps(record) + "\n", encoding="utf-8")
            with self.assertRaises(AuditJournalUnreadable):
                AuditStore(str(path))

    def test_missing_journal_reports_zero_rather_than_inventing(self):
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            store = AuditStore(str(Path(tmp) / "nope.jsonl"))
            self.assertEqual(0, len(store))
            self.assertFalse(store.available)
            payload = _get(store, AUDIT_EVENTS_PATH)
            self.assertEqual(0, payload["total"])
            self.assertEqual([], payload["events"])

    def test_a_journal_corrupted_after_startup_yields_a_500_not_partial_data(self):
        """The realistic corruption path: valid at boot, damaged on disk later."""
        import os
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "journal.jsonl"
            path.write_text(HEALTHY_JOURNAL.read_text(encoding="utf-8"), encoding="utf-8")
            store = AuditStore(str(path))
            self.assertEqual(264, len(store))

            path.write_text("{broken\n", encoding="utf-8")
            os.utime(path, (0, 0))  # force a detectable change
            with self.assertRaises(ApiError) as ctx:
                _get(store, AUDIT_EVENTS_PATH)
            self.assertEqual(500, ctx.exception.status)
            self.assertEqual("audit_journal_unreadable", ctx.exception.code)
            self.assertNotIn("events", ctx.exception.payload())


# ---------------------------------------------------------------------------
# Phase 2 -- ordered run trail
# ---------------------------------------------------------------------------

class TestAuditStoreTrail(_StoreTestCase):
    def test_trail_is_ordered_by_stage_then_window(self):
        trail = self.store.run_trail(RUN_ID)
        self.assertIsNotNone(trail)
        self.assertEqual(44, trail["window_count"])
        self.assertEqual(264, trail["event_count"])
        self.assertEqual(
            ["expected", "observed", "comparison", "ml", "risk", "explanation"],
            trail["windows"][0].stage_names(),
        )

    def test_trail_stages_follow_the_canonical_order(self):
        trail = self.store.run_trail(RUN_ID)
        order = list(AUDIT_STAGE_ORDER)
        for window in trail["windows"]:
            positions = [order.index(stage) for stage in window.stage_names()]
            self.assertEqual(sorted(positions), positions,
                             "stages must be emitted in lifecycle order")

    def test_trail_windows_are_in_ascending_window_order(self):
        trail = self.store.run_trail(RUN_ID)
        indexes = [w.window_index for w in trail["windows"]]
        self.assertEqual(sorted(indexes), indexes)
        self.assertEqual(list(range(44)), indexes)

    def test_trail_is_deterministic_across_repeated_reads(self):
        first = self.store.run_trail(RUN_ID)
        second = self.store.run_trail(RUN_ID)
        self.assertEqual(
            [(w.window_index, w.stage_names()) for w in first["windows"]],
            [(w.window_index, w.stage_names()) for w in second["windows"]],
        )

    def test_unknown_run_has_no_trail(self):
        self.assertIsNone(self.store.run_trail("no-such-run"))

    def test_trail_does_not_fabricate_missing_stages(self):
        """A response stage must be absent, not emitted empty."""
        trail = self.store.run_trail(RUN_ID)
        for window in trail["windows"]:
            for stage in window.stage_names():
                self.assertNotIn(stage, ("response", "authorization", "execution"))
        self.assertNotIn("response", trail["stages_present"])
        self.assertNotIn("authorization", trail["stages_present"])
        self.assertNotIn("execution", trail["stages_present"])


# ---------------------------------------------------------------------------
# Phase 3 -- route contract
# ---------------------------------------------------------------------------

class TestAuditApiRoutes(_StoreTestCase):
    def test_list_route(self):
        payload = _get(self.store, AUDIT_EVENTS_PATH, limit=3)
        self.assertEqual("audit-events", payload["api"])
        self.assertEqual(3, payload["count"])
        self.assertEqual(list(AUDIT_STAGE_ORDER), payload["stage_order"])

    def test_detail_route_returns_the_persisted_record(self):
        event_id = self.events[0].event_id
        payload = _get(self.store, f"{AUDIT_EVENTS_PATH}/{event_id}")
        self.assertEqual(self.events[0].to_dict(), payload)
        for key in ("event_id", "event_type", "source", "authoritative",
                    "identity", "schema_version", "recorded_at"):
            self.assertIn(key, payload)

    def test_detail_route_retains_original_identity(self):
        event_id = self.by_id and next(
            e.event_id for e in self.events if e.event_type == EVENT_COMPARISON
        )
        payload = _get(self.store, f"{AUDIT_EVENTS_PATH}/{event_id}")
        self.assertEqual(event_id, payload["event_id"])
        self.assertEqual(RUN_ID, payload["identity"]["dataset_run_id"])
        self.assertEqual(EXPERIMENT_ID, payload["identity"]["experiment_id"])
        self.assertEqual(SEQUENCE, payload["identity"]["sequence"])

    def test_unknown_event_id_is_a_structured_404(self):
        with self.assertRaises(ApiError) as ctx:
            _get(self.store, f"{AUDIT_EVENTS_PATH}/audit-ffffffffffffffffffffffffffffffff")
        self.assertEqual(404, ctx.exception.status)
        self.assertEqual("audit_event_not_found", ctx.exception.code)
        self.assertIn("error", ctx.exception.payload())

    def test_unknown_run_is_a_structured_404(self):
        with self.assertRaises(ApiError) as ctx:
            _get(self.store, "/api/v1/runs/no-such-run/audit")
        self.assertEqual(404, ctx.exception.status)
        self.assertEqual("audit_run_not_found", ctx.exception.code)

    def test_unknown_audit_route_is_a_404(self):
        with self.assertRaises(ApiError) as ctx:
            _get(self.store, "/api/v1/audit/nope")
        self.assertEqual(404, ctx.exception.status)
        self.assertIn(ctx.exception.code, ("unknown_route", "unknown_resource"))

    def test_bad_filter_is_a_structured_400(self):
        for params in (
            {"authoritative": "maybe"},
            {"sequence": "not-a-number"},
            {"limit": "0"},
            {"offset": "-1"},
            {"window_index": "abc"},
        ):
            with self.subTest(params=params):
                with self.assertRaises(ApiError) as ctx:
                    _get(self.store, AUDIT_EVENTS_PATH, **params)
                self.assertEqual(400, ctx.exception.status)
                self.assertEqual("invalid_query_parameter", ctx.exception.code)

    def test_run_trail_route(self):
        payload = _get(self.store, f"/api/v1/runs/{RUN_ID}/audit", window_index=3)
        self.assertEqual("audit-run-trail", payload["api"])
        self.assertEqual(RUN_ID, payload["run_id"])
        self.assertEqual(1, payload["window_count"])
        window = payload["windows"][0]
        self.assertEqual(3, window["window_index"])
        self.assertEqual(
            ["expected", "observed", "comparison", "ml", "risk", "explanation"],
            window["stage_names"],
        )
        for stage in window["stages"]:
            self.assertTrue(stage["present"])
            self.assertEqual(len(stage["events"]), stage["event_count"])

    def test_run_trail_route_can_filter_to_one_stage(self):
        payload = _get(
            self.store, f"/api/v1/runs/{RUN_ID}/audit",
            window_index=0, event_type=EVENT_OBSERVED_STATE,
        )
        self.assertEqual(1, payload["window_count"])
        self.assertEqual(1, payload["event_count"])
        self.assertEqual(["observed"], payload["windows"][0]["stage_names"])

    def test_is_audit_path_recognises_only_audit_routes(self):
        for path in (
            AUDIT_EVENTS_PATH,
            f"{AUDIT_EVENTS_PATH}/audit-abc",
            AUDIT_RUNS_PATH,
            f"/api/v1/runs/{RUN_ID}/audit",
        ):
            self.assertTrue(is_audit_path(path), path)
        for path in ("/api/v1/health", "/api/v1/metrics", "/api/v1/evidence/x", "/api/health"):
            self.assertFalse(is_audit_path(path), path)

    def test_audit_surface_requires_a_wired_store(self):
        class _Ctx:
            audit_store = None

        with self.assertRaises(ApiError) as ctx:
            handle_v1_audit(_Ctx(), AUDIT_EVENTS_PATH)
        self.assertEqual(503, ctx.exception.status)
        self.assertEqual("audit_unavailable", ctx.exception.code)

    def test_audit_routes_work_through_the_v1_dispatcher(self):
        class _Ctx:
            audit_store = self.store

        content, content_type = handle_v1_get(_Ctx(), AUDIT_EVENTS_PATH, {"limit": 2})
        self.assertEqual("application/json", content_type)
        self.assertEqual(2, content["count"])
        self.assertEqual(264, content["total"])


# ---------------------------------------------------------------------------
# Phase 4 -- provenance preservation
# ---------------------------------------------------------------------------

class TestAuditApiProvenance(_StoreTestCase):
    def test_required_provenance_table(self):
        seen = {e.event_type: (e.source, e.authoritative) for e in self.events}
        for event_type, (source, authoritative) in EXPECTED_PROVENANCE.items():
            if event_type in (EVENT_RESPONSE_PROPOSAL, EVENT_ML_FAILURE):
                # not present in the healthy run: no proposal was recorded, and
                # the healthy run has ml_result rather than ml_failure. Both are
                # asserted in their own test classes.
                continue
            with self.subTest(event_type=event_type):
                self.assertEqual((source, authoritative), seen[event_type])

    def test_observed_is_the_only_authoritative_event(self):
        authoritative = {e.event_type for e in self.events if e.authoritative}
        self.assertEqual({EVENT_OBSERVED_STATE}, authoritative)

    def test_list_rows_preserve_source_and_authoritative(self):
        payload = _get(self.store, AUDIT_EVENTS_PATH, limit=500)
        for row in payload["events"]:
            with self.subTest(event_type=row["event_type"]):
                self.assertIn(row["source"], {
                    SOURCE_EXPECTED, SOURCE_OBSERVED, SOURCE_COMPARISON,
                    SOURCE_ML, SOURCE_RISK, SOURCE_EXPLAINABILITY,
                    SOURCE_RESPONSE_RECOMMENDATION,
                })
                expected = EXPECTED_PROVENANCE[row["event_type"]][1]
                self.assertEqual(expected, row["authoritative"])

    def test_comparison_is_never_relabelled_as_observation(self):
        payload = _get(
            self.store, f"/api/v1/runs/{RUN_ID}/audit",
            window_index=0, event_type=EVENT_COMPARISON,
        )
        stage = payload["windows"][0]["stages"][0]
        self.assertEqual("comparison", stage["stage"])
        event = stage["events"][0]
        self.assertEqual(SOURCE_COMPARISON, event["source"])
        self.assertNotEqual(SOURCE_OBSERVED, event["source"])
        self.assertFalse(event["authoritative"])

    def test_ml_is_never_presented_as_authoritative(self):
        payload = _get(
            self.store, f"/api/v1/runs/{RUN_ID}/audit",
            window_index=0, event_type=EVENT_ML_RESULT,
        )
        event = payload["windows"][0]["stages"][0]["events"][0]
        self.assertEqual(SOURCE_ML, event["source"])
        self.assertFalse(event["authoritative"])

    def test_detail_payload_keeps_comparison_provenance(self):
        event = next(e for e in self.events if e.event_type == EVENT_COMPARISON)
        payload = _get(self.store, f"{AUDIT_EVENTS_PATH}/{event.event_id}")
        self.assertEqual(SOURCE_COMPARISON, payload["source"])
        self.assertFalse(payload["authoritative"])
        variables = payload["comparison"]["variables"]
        self.assertTrue(variables)
        for variable in variables:
            with self.subTest(variable=variable["variable"]):
                if variable["observed_value"] is None:
                    self.assertIsNone(variable["observed_value_source"])
                    self.assertFalse(variable["observed_value_authoritative"])

    def test_missing_values_stay_null(self):
        event = next(
            e for e in self.events
            if e.event_type == EVENT_COMPARISON
            and any(v["observed_value"] is None
                    for v in e.comparison["variables"])
        )
        payload = _get(self.store, f"{AUDIT_EVENTS_PATH}/{event.event_id}")
        absent = [v for v in payload["comparison"]["variables"] if v["observed_value"] is None]
        self.assertTrue(absent)
        for variable in absent:
            self.assertIsNone(variable["observed_value"])
            self.assertIsNone(variable["observed_value_source"])
            self.assertFalse(variable["observed_value_authoritative"])

    def test_expected_event_carries_no_observed_evidence(self):
        event = next(e for e in self.events if e.event_type == EVENT_EXPECTED_STATE)
        payload = _get(self.store, f"{AUDIT_EVENTS_PATH}/{event.event_id}")
        self.assertIsNone(payload["observed_ref"])
        self.assertIsNone(payload["comparison"])
        self.assertEqual(SOURCE_EXPECTED, payload["source"])
        self.assertFalse(payload["authoritative"])


# ---------------------------------------------------------------------------
# Phase 6 -- ML failure stays queryable
# ---------------------------------------------------------------------------

class TestAuditApiMlFailure(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.store = AuditStore(str(ML_FAILURE_JOURNAL))
        cls.events = cls.store.select()

    def test_broken_model_lifecycle_is_fully_queryable(self):
        trail = self.store.run_trail(RUN_ID)
        self.assertEqual(44, trail["window_count"])
        self.assertEqual(
            ["expected", "observed", "comparison", "ml", "risk", "explanation"],
            trail["windows"][0].stage_names(),
        )
        self.assertIn("ml", trail["stages_present"])

    def test_ml_failure_is_recorded_in_the_ml_stage(self):
        failures = [e for e in self.events if e.event_type == EVENT_ML_FAILURE]
        self.assertEqual(44, len(failures))
        self.assertNotIn(EVENT_ML_RESULT, {e.event_type for e in self.events})
        for event in failures:
            self.assertEqual(SOURCE_ML, event.source)
            self.assertFalse(event.authoritative)
            self.assertTrue(event.provenance["authoritative_path_intact"])
            self.assertIn("ValueError", event.provenance["failure"])

    def test_authoritative_path_survives_the_ml_failure(self):
        observed = [e for e in self.events if e.event_type == EVENT_OBSERVED_STATE]
        comparisons = [e for e in self.events if e.event_type == EVENT_COMPARISON]
        risks = [e for e in self.events if e.event_type == EVENT_RISK_ASSESSMENT]
        explanations = [e for e in self.events if e.event_type == EVENT_EXPLANATION]
        self.assertEqual(44, len(observed))
        self.assertEqual(44, len(comparisons))
        self.assertEqual(44, len(risks))
        self.assertEqual(44, len(explanations))
        self.assertTrue(all(e.authoritative for e in observed))

    def test_ml_failure_is_reachable_through_the_api(self):
        payload = _get(self.store, AUDIT_EVENTS_PATH, event_type=EVENT_ML_FAILURE, limit=2)
        self.assertEqual(44, payload["total"])
        self.assertEqual("ml_failure", payload["events"][0]["event_type"])
        self.assertEqual("ml", payload["events"][0]["stage"])
        self.assertFalse(payload["events"][0]["authoritative"])

        event_id = payload["events"][0]["event_id"]
        detail = _get(self.store, f"{AUDIT_EVENTS_PATH}/{event_id}")
        self.assertEqual(EVENT_ML_FAILURE, detail["event_type"])
        self.assertIn("ValueError", detail["provenance"]["failure"])
        self.assertTrue(detail["provenance"]["authoritative_path_intact"])
        self.assertIsNone(detail["observed_ref"])


# ---------------------------------------------------------------------------
# Phase 7 -- real recorded evidence, end to end
# ---------------------------------------------------------------------------

class TestAuditApiRealEvidence(unittest.TestCase):
    """Journal -> store -> API must lose nothing and invent nothing."""

    @classmethod
    def setUpClass(cls):
        cls.store = AuditStore(str(HEALTHY_JOURNAL))
        cls.raw = [json.loads(line) for line in
                   HEALTHY_JOURNAL.read_text(encoding="utf-8").splitlines() if line.strip()]

    def test_every_persisted_record_is_served(self):
        payload = _get(self.store, AUDIT_EVENTS_PATH, limit=500)
        self.assertEqual(len(self.raw), payload["total"])
        self.assertEqual(
            {record["event_id"] for record in self.raw},
            {row["event_id"] for row in payload["events"]},
        )

    def test_every_persisted_record_round_trips_byte_for_byte(self):
        by_id = {record["event_id"]: record for record in self.raw}
        for record in self.raw:
            with self.subTest(event_id=record["event_id"]):
                served = _get(self.store, f"{AUDIT_EVENTS_PATH}/{record['event_id']}")
                self.assertEqual(record, served)
                self.assertEqual(record["event_id"], by_id[record["event_id"]]["event_id"])

    def test_journal_and_api_report_the_same_ledger(self):
        journal_events = AuditJournal(str(HEALTHY_JOURNAL)).read()
        self.assertEqual(len(journal_events), len(self.store))
        self.assertEqual(
            [e.to_dict() for e in journal_events],
            [e.to_dict() for e in self.store.select()],
        )

    def test_listing_preserves_every_persisted_field(self):
        raw = next(r for r in self.raw if r["event_type"] == EVENT_OBSERVED_STATE)
        payload = _get(self.store, AUDIT_EVENTS_PATH, event_type=EVENT_OBSERVED_STATE, limit=1)
        row = payload["events"][0]
        # the persisted record nests identity; the list row flattens it. Both must
        # carry identical values, including the window bounds.
        for key in ("event_id", "event_type", "source", "authoritative", "recorded_at"):
            with self.subTest(field=key):
                self.assertEqual(raw[key], row[key])
        for key in ("dataset_run_id", "sequence", "experiment_id", "attempt_number",
                    "window_index", "window_start_ns", "window_end_ns"):
            with self.subTest(identity_field=key):
                self.assertEqual(raw["identity"][key], row[key])

    def test_observation_journal_is_not_mistaken_for_analysis_evidence(self):
        """The two journals have different schemas; they must not be conflated."""
        self.assertTrue(OBSERVATION_JOURNAL.exists())
        self.assertTrue(OBSERVATION_JOURNAL.read_text().strip())
        # The observation journal has no ``authoritative`` field and no analysis
        # identity, so it is refused rather than reinterpreted as analysis
        # evidence. Silently coercing it would be exactly the source confusion
        # this milestone forbids.
        with self.assertRaises(AuditJournalUnreadable) as ctx:
            AuditStore(str(OBSERVATION_JOURNAL))
        self.assertIn("authoritative", str(ctx.exception))
        self.assertEqual(264, len(AuditStore(str(HEALTHY_JOURNAL))))

    def test_observation_journal_is_untouched_by_analysis_reads(self):
        before = OBSERVATION_JOURNAL.read_bytes()
        _get(self.store, AUDIT_EVENTS_PATH, limit=10)
        self.assertEqual(before, OBSERVATION_JOURNAL.read_bytes())


# ---------------------------------------------------------------------------
# Phase 6 -- isolation: a read is never an action
# ---------------------------------------------------------------------------

class TestAuditApiIsolation(unittest.TestCase):
    MODULES = (
        "correlation/api/audit_store.py",
        "correlation/api/audit_routes.py",
    )

    def _source(self, name):
        return (REPO_ROOT / name).read_text(encoding="utf-8")

    def test_store_and_routes_do_not_import_execution(self):
        for name in self.MODULES:
            tree = ast.parse(self._source(name))
            for node in ast.walk(tree):
                if isinstance(node, ast.ImportFrom):
                    with self.subTest(module=name, imported=node.module):
                        self.assertNotIn("execution", node.module or "")
                elif isinstance(node, ast.Import):
                    for alias in node.names:
                        with self.subTest(module=name, imported=alias.name):
                            self.assertNotIn("execution", alias.name)

    def test_store_and_routes_do_not_import_a_response_engine(self):
        for name in self.MODULES:
            text = self._source(name)
            for forbidden in ("response.engine", "ResponseEngine", "correlation.response.engine"):
                with self.subTest(module=name, token=forbidden):
                    self.assertNotIn(forbidden, text)

    def test_store_and_routes_never_call_enforcement_or_controllers(self):
        """No handler may reach an action verb, a controller or a journal write.

        Checked on the *call target*, so ordinary in-memory ``list.append`` on
        this module's own stage buckets is not mistaken for a journal write; a
        write is only forbidden when the receiver is the journal/ledger/store.
        """
        write_receivers = ("journal", "ledger", "store", "self.journal")
        action_calls = (
            "execute", "authorize", "approve", "request_approval", "enforce",
            "attach_xdp", "xdp_attach", "detach", "drop", "record_event",
            "extend", "write", "writelines", "truncate",
        )
        for name in self.MODULES:
            tree = ast.parse(self._source(name))
            for node in ast.walk(tree):
                if not isinstance(node, ast.Call):
                    continue
                func = node.func
                if isinstance(func, ast.Attribute):
                    target, receiver = func.attr, func.value
                elif isinstance(func, ast.Name):
                    target, receiver = func.id, None
                else:
                    continue
                receiver_name = ""
                if isinstance(receiver, ast.Name):
                    receiver_name = receiver.id
                elif isinstance(receiver, ast.Attribute):
                    receiver_name = receiver.attr
                if target in ("append", "extend", "write"):
                    for needle in write_receivers:
                        with self.subTest(module=name, call=target, receiver=receiver_name):
                            self.assertNotIn(needle, receiver_name)
                else:
                    with self.subTest(module=name, call=target):
                        self.assertNotIn(target, action_calls)

    def test_store_opens_files_read_only(self):
        source = self._source("correlation/api/audit_store.py")
        self.assertNotIn('"w"', source)
        self.assertNotIn("'w'", source)
        self.assertNotIn("os.remove", source)
        self.assertNotIn("shutil", source)

    def test_reads_do_not_change_observed_or_expected_state(self):
        before = OBSERVATION_JOURNAL.read_bytes()
        store = AuditStore(str(HEALTHY_JOURNAL))
        events = store.select()
        observed_before = [e.observed_ref for e in events if e.observed_ref]
        expected_before = [e.expected_ref for e in events if e.expected_ref]
        _get(store, AUDIT_EVENTS_PATH, limit=100)
        _get(store, f"/api/v1/runs/{RUN_ID}/audit")
        events_after = store.select()
        self.assertEqual(observed_before, [e.observed_ref for e in events_after if e.observed_ref])
        self.assertEqual(expected_before, [e.expected_ref for e in events_after if e.expected_ref])
        self.assertEqual(before, OBSERVATION_JOURNAL.read_bytes())

    def test_no_http_verb_other_than_get_reaches_the_audit_store(self):
        """POST/PUT/DELETE are refused by the transport before any handler."""
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            completed = subprocess.run(
                [sys.executable, "-c",
                 "import sys; sys.path.insert(0, %r);"
                 "from correlation.api.app import DashboardHandler;"
                 "print(hasattr(DashboardHandler, 'do_POST'),"
                 " hasattr(DashboardHandler, 'do_PUT'),"
                 " hasattr(DashboardHandler, 'do_DELETE'))" % str(REPO_ROOT)],
                capture_output=True, text=True, cwd=REPO_ROOT,
            )
            self.assertEqual(0, completed.returncode, completed.stderr)
            self.assertEqual("True True True", completed.stdout.strip())

    def test_store_module_never_appends_to_its_journal(self):
        """The store borrows a journal and only ever reads it.

        Checked structurally: no write call targets the journal, and no file is
        ever opened for writing.
        """
        tree = ast.parse(self._source("correlation/api/audit_store.py"))
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                func = node.func
                receiver = func.value if isinstance(func, ast.Attribute) else None
                receiver_name = getattr(receiver, "attr", getattr(receiver, "id", ""))
                target = getattr(func, "attr", getattr(func, "id", ""))
                if "journal" in str(receiver_name):
                    with self.subTest(call=target, receiver=receiver_name):
                        self.assertNotIn(target, ("append", "extend", "write", "clear"))
            if isinstance(node, ast.Constant) and isinstance(node.value, str):
                with self.subTest(value=node.value):
                    self.assertNotIn(node.value, ("w", "a", "w+", "r+"))
        source = self._source("correlation/api/audit_store.py")
        self.assertIn("self.journal.read()", source)
        for forbidden in ("os.remove", "os.unlink", "shutil", "os.rename"):
            with self.subTest(token=forbidden):
                self.assertNotIn(forbidden, source)


# ---------------------------------------------------------------------------
# Phase 5 -- response proposal join (read-only)
# ---------------------------------------------------------------------------

class TestAuditResponseJoin(_StoreTestCase):
    def test_join_reports_real_absence_without_a_ledger(self):
        result = self.store.response_lifecycle("RR-ANY")
        self.assertFalse(result["available"])
        self.assertEqual("RR-ANY", result["recommendation_id"])
        self.assertIsNone(result["reason"]) if False else None
        self.assertTrue(result["reason"])
        self.assertEqual([], result["stages"])
        self.assertEqual([], result["events"])

    def test_join_reports_absence_for_a_missing_reference(self):
        result = self.store.response_lifecycle("")
        self.assertFalse(result["available"])
        self.assertIn("no response_proposal_ref", result["reason"])

    def test_join_exposes_real_response_records_when_a_ledger_is_attached(self):
        sys.path.insert(0, str(REPO_ROOT / "tests" / "fixtures" / "response"))
        from response_fixtures import assessment_for_posture, engine  # noqa: E402

        from correlation.response import ROLE_ANALYST
        from correlation.response.authorization import auth_context

        response_engine = engine()
        plan = response_engine.plan(assessment_for_posture("WEAK"))
        recommendation = plan.by_id()["RR-RISK-PFS-DISABLED"]
        store = AuditStore(str(HEALTHY_JOURNAL), response_ledger=response_engine.ledger)
        if sys.path[0].endswith("response"):
            sys.path.pop(0)
        rid = recommendation.recommendation_id

        # proposed only
        before = store.response_lifecycle(rid)
        self.assertTrue(before["available"])
        self.assertEqual(1, before["event_count"])
        self.assertEqual("RECOMMENDATION_CREATED", before["events"][0]["event_type"])
        self.assertEqual(["response"], before["stages"])
        self.assertNotIn("authorization", before["stages"])
        self.assertNotIn("execution", before["stages"])

        # a real approval is still proposal-side
        approval = response_engine.request_approval(recommendation, "analyst-1", "proceed")
        response_engine.approve(approval, recommendation, "analyst-1",
                                roles=(ROLE_ANALYST,))
        approved = store.response_lifecycle(rid)
        self.assertTrue(approved["available"])
        self.assertGreater(approved["event_count"], before["event_count"])
        self.assertEqual(["response"], approved["stages"])
        self.assertNotIn("authorization", approved["stages"])

        # a real authorization record is surfaced as the authorization stage
        response_engine.authorize(
            recommendation, auth_context("analyst-1", (ROLE_ANALYST,))
        )
        authorized = store.response_lifecycle(rid)
        self.assertTrue(authorized["available"])
        self.assertEqual(["response", "authorization"], authorized["stages"])
        self.assertNotIn("execution", authorized["stages"])
        self.assertTrue(authorized["chain_verified"])
        # the store reports the response layer's records, it does not author them
        self.assertTrue(
            all("previous_hash" in event and "event_hash" in event
                for event in authorized["events"])
        )

    def test_join_never_invents_an_authorization_or_execution(self):
        store = AuditStore(str(HEALTHY_JOURNAL))
        result = store.response_lifecycle("RR-NOT-RECORDED")
        self.assertEqual([], result["events"])
        for event_type in ("AUTHORIZATION_CHECKED", "EXECUTION_SUCCEEDED",
                           "EXECUTION_REQUESTED"):
            self.assertNotIn(event_type, str(result))


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
