"""Correlation data models (canonical Phase 2 contract)."""

from .correlation import (  # noqa: F401
    CORRELATION_STATUS_MATCH,
    CORRELATION_STATUS_MISMATCH,
    CORRELATION_STATUS_NOT_APPLICABLE,
    CORRELATION_STATUS_NOT_EVALUATED,
    CORRELATION_STATUS_PARTIAL,
    CORRELATION_STATUS_UNKNOWN,
    CORRELATION_STATUSES,
    CorrelationInput,
    CorrelationResult,
)
from .evidence import EvidenceRef  # noqa: F401
from .expected import (  # noqa: F401
    ALLOWED_ADDRESS_FAMILIES,
    ALLOWED_ESP_DH_GROUPS,
    ALLOWED_ESP_ENCRYPTION,
    ALLOWED_ESP_INTEGRITY,
    ALLOWED_IKE_DH_GROUPS,
    ALLOWED_IKE_ENCRYPTION,
    ALLOWED_IKE_INTEGRITY,
    ALLOWED_IKE_VERSIONS,
    ALLOWED_MODES,
    ALLOWED_TRAFFIC_PROFILES,
    CANONICAL_VARIABLES,
    TRAFFIC_DURATION_RANGE,
    TRAFFIC_PORT_RANGE,
    EspExpected,
    ExpectedState,
    IkeExpected,
    TrafficExpected,
)
from .features import FEATURE_SCHEMA_VERSION_V2, LiveFeatureWindow  # noqa: F401
from .identity import CorrelationIdentity  # noqa: F401
from .ml import MLResult  # noqa: F401
from .observed import (  # noqa: F401
    DOCUMENTED_TRANSITIONS,
    SPI_DIRECTION_A_TO_B,
    SPI_DIRECTION_B_TO_A,
    SPI_DIRECTIONS,
    TRANSITION_ACTIVE,
    TRANSITION_INACTIVE,
    TRANSITION_IPSEC_TRAFFIC_OBSERVED,
    TRANSITION_NO_TRAFFIC,
    TRANSITION_SPI_OBSERVED,
    ObservedState,
    SpiObservation,
    TransitionObservation,
)
from .observability import (  # noqa: F401
    AUDIT_ONLY,
    DIRECTLY_OBSERVABLE,
    INDIRECTLY_OBSERVABLE,
    NOT_CURRENTLY_OBSERVABLE,
    OBSERVABILITY,
    TRACEABILITY,
    Observability,
    classification_of,
)

__all__ = [
    "CORRELATION_STATUS_MATCH",
    "CORRELATION_STATUS_MISMATCH",
    "CORRELATION_STATUS_NOT_APPLICABLE",
    "CORRELATION_STATUS_NOT_EVALUATED",
    "CORRELATION_STATUS_PARTIAL",
    "CORRELATION_STATUS_UNKNOWN",
    "CORRELATION_STATUSES",
    "CorrelationInput",
    "CorrelationResult",
    "EvidenceRef",
    "ALLOWED_ADDRESS_FAMILIES",
    "ALLOWED_ESP_DH_GROUPS",
    "ALLOWED_ESP_ENCRYPTION",
    "ALLOWED_ESP_INTEGRITY",
    "ALLOWED_IKE_DH_GROUPS",
    "ALLOWED_IKE_ENCRYPTION",
    "ALLOWED_IKE_INTEGRITY",
    "ALLOWED_IKE_VERSIONS",
    "ALLOWED_MODES",
    "ALLOWED_TRAFFIC_PROFILES",
    "CANONICAL_VARIABLES",
    "TRAFFIC_DURATION_RANGE",
    "TRAFFIC_PORT_RANGE",
    "EspExpected",
    "ExpectedState",
    "IkeExpected",
    "TrafficExpected",
    "FEATURE_SCHEMA_VERSION_V2",
    "LiveFeatureWindow",
    "CorrelationIdentity",
    "MLResult",
    "DOCUMENTED_TRANSITIONS",
    "SPI_DIRECTION_A_TO_B",
    "SPI_DIRECTION_B_TO_A",
    "SPI_DIRECTIONS",
    "TRANSITION_ACTIVE",
    "TRANSITION_INACTIVE",
    "TRANSITION_IPSEC_TRAFFIC_OBSERVED",
    "TRANSITION_NO_TRAFFIC",
    "TRANSITION_SPI_OBSERVED",
    "ObservedState",
    "SpiObservation",
    "TransitionObservation",
    "AUDIT_ONLY",
    "DIRECTLY_OBSERVABLE",
    "INDIRECTLY_OBSERVABLE",
    "NOT_CURRENTLY_OBSERVABLE",
    "OBSERVABILITY",
    "TRACEABILITY",
    "Observability",
    "classification_of",
]