"""Phase 10 — production streaming layer.

Deterministic, versioned streaming contract (``stream-schema-v1``), event
producer/consumer with duplicate protection, retry/backoff, dead-letter,
backpressure and offset tracking — all wired to explicit configuration.
"""

from .backpressure import (  # noqa: F401
    BLOCK,
    BUFFER,
    DLQ,
    DROP,
    BackpressureState,
    OverflowAction,
    default_overflow_for,
)
from .config import StreamingConfig  # noqa: F401
from .consumer import ConsumeLoop, EventHandler  # noqa: F401
from .dead_letter import DLQ_SCHEMA_VERSION, DeadLetterQueue, DeadLetterRecord  # noqa: F401
from .dedup import Deduplicator, make_dedup_key  # noqa: F401
from .models import (  # noqa: F401
    EVENT_TYPES,
    EVENT_TYPE_APPROVAL,
    EVENT_TYPE_AUDIT,
    EVENT_TYPE_AUTHORIZATION,
    EVENT_TYPE_CORRELATION,
    EVENT_TYPE_EVIDENCE,
    EVENT_TYPE_FEATURE_WINDOW,
    EVENT_TYPE_IKE,
    EVENT_TYPE_ML_RESULT,
    EVENT_TYPE_PACKET,
    EVENT_TYPE_RESPONSE_EXECUTION,
    EVENT_TYPE_RECOMMENDATION,
    EVENT_TYPE_RISK,
    EVENT_TYPE_STATE,
    EVENT_TYPE_XAI,
    STREAM_SCHEMA_VERSION,
    StreamEvent,
    make_payload_event,
    validate_event_type,
)
from .live_adapter import (  # noqa: F401
    CLASS_ESP,
    CLASS_IKE,
    CLASS_IKE_NAT_T,
    CLASSIFICATIONS,
    CLASSIFICATION_ESP,
    CLASSIFICATION_ESP_IN_UDP,
    CLASSIFICATION_IKE,
    CLASSIFICATION_UNKNOWN,
    CLASSIFICATION_AH,
    NatTClassification,
    XdpEventAdapter,
    classify_udp_4500,
)
from .ml_provider import (  # noqa: F401
    MLInferenceProvider,
    MLProviderResult,
    MODE_REAL_MODEL,
    MODE_TEST_DOUBLE,
    MODE_UNAVAILABLE,
    STATUS_COMPLETED,
    STATUS_FAILED,
    STATUS_UNREQUESTED,
    TestDoubleClassifierModel,
    TestDoubleWindowBuilder,
)
from .offsets import OffsetTracker  # noqa: F401
from .partitioning import partition_for, partition_key, partitioning_notes  # noqa: F401
from .pipeline import (  # noqa: F401
    ContinuousPipeline,
    ObservedStateBuilder,
    PipelineResult,
)
from .producer import EventProducer, EventTransport, MemoryTransport  # noqa: F401
from .retry import RetryController, RetryPolicy, RetryState  # noqa: F401
from .schema import (  # noqa: F401
    STREAM_SCHEMA_CONTRACT,
    STREAM_SCHEMA_NAME,
    canonical_field_order,
    default_event_type_to_topic,
    deserialize_jsonl,
    roundtrip_identity,
    schema_contract,
    serialize_jsonl,
    topic_for_event_type,
    validate_event,
)
from .topics import (  # noqa: F401
    DEFAULT_TOPICS,
    TOPIC_AUDIT,
    TOPIC_CORRELATION,
    TOPIC_EVIDENCE,
    TOPIC_FEATURES,
    TOPIC_ML,
    TOPIC_RAW,
    TOPIC_RESPONSE,
    TOPIC_RISK,
    TOPIC_STATE,
    TOPIC_XAI,
    EventTopicMap,
)
from .windowing import (  # noqa: F401
    CLASS_AH,
    CLASS_ESP,
    CLASS_IKE,
    CLASS_IKE_NAT_T,
    CLASS_OTHER,
    EmissionPolicy,
    WINDOW_LOOKBACK_DEFAULT,
    WINDOW_SIZE_MS_DEFAULT,
    WindowEngine,
    WindowRecord,
)

__all__ = [
    "BLOCK",
    "BUFFER",
    "DLQ",
    "DROP",
    "BackpressureState",
    "ConsumeLoop",
    "DLQ_SCHEMA_VERSION",
    "DeadLetterQueue",
    "DeadLetterRecord",
    "Deduplicator",
    "DEFAULT_TOPICS",
    "EVENT_TYPES",
    "EVENT_TYPE_APPROVAL",
    "EVENT_TYPE_AUDIT",
    "EVENT_TYPE_AUTHORIZATION",
    "EVENT_TYPE_CORRELATION",
    "EVENT_TYPE_EVIDENCE",
    "EVENT_TYPE_FEATURE_WINDOW",
    "EVENT_TYPE_IKE",
    "EVENT_TYPE_ML_RESULT",
    "EVENT_TYPE_PACKET",
    "EVENT_TYPE_RESPONSE_EXECUTION",
    "EVENT_TYPE_RECOMMENDATION",
    "EVENT_TYPE_RISK",
    "EVENT_TYPE_STATE",
    "EVENT_TYPE_XAI",
    "EventHandler",
    "EventProducer",
    "EventTopicMap",
    "EventTransport",
    "MemoryTransport",
    "OffsetTracker",
    "OverflowAction",
    "RetryController",
    "RetryPolicy",
    "RetryState",
    "STREAM_SCHEMA_CONTRACT",
    "STREAM_SCHEMA_NAME",
    "STREAM_SCHEMA_VERSION",
    "StreamEvent",
    "StreamingConfig",
    "TOPIC_AUDIT",
    "TOPIC_CORRELATION",
    "TOPIC_EVIDENCE",
    "TOPIC_FEATURES",
    "TOPIC_ML",
    "TOPIC_RAW",
    "TOPIC_RESPONSE",
    "TOPIC_RISK",
    "TOPIC_STATE",
    "TOPIC_XAI",
    "canonical_field_order",
    "default_event_type_to_topic",
    "default_overflow_for",
    "deserialize_jsonl",
    "make_dedup_key",
    "make_payload_event",
    "partition_for",
    "partition_key",
    "partitioning_notes",
    "roundtrip_identity",
    "schema_contract",
    "serialize_jsonl",
    "topic_for_event_type",
    "validate_event",
    "validate_event_type",
    "CLASS_AH",
    "CLASS_ESP",
    "CLASS_IKE",
    "CLASS_IKE_NAT_T",
    "CLASS_OTHER",
    "EmissionPolicy",
    "WINDOW_LOOKBACK_DEFAULT",
    "WINDOW_SIZE_MS_DEFAULT",
    "WindowEngine",
    "WindowRecord",
]