connections {

    gw-a-to-gw-b {

        version = 2
        local_addrs = 192.168.100.1
        remote_addrs = 192.168.100.2

        local {
            auth = psk
            id = gw-a
        }

        remote {
            auth = psk
            id = gw-b
        }

        children {

            lan-a-to-lan-b {

                local_ts = 10.10.1.0/24
                remote_ts = 10.10.2.0/24

                esp_proposals = aes256gcm16-modp2048
                start_action = trap
            }
        }

        proposals = aes256-sha256-modp2048
    }
}
