"""Mission context: explicit, operator-supplied asset context (not inferred).

Re-exports the small public surface. See :mod:`correlation.mission.models` for
why this boundary exists, and :mod:`correlation.mission.contextualize` for the
formula.
"""

from .contextualize import (
    CATEGORY_WEIGHTS,
    FORMULA,
    MAX_UPLIFT_BP,
    NEUTRAL_BP,
    TECHNICAL_SCORE_CAP,
    WEIGHT_CEILING,
    WEIGHT_FLOOR,
    WEIGHT_SPAN,
    ContextualizedRisk,
    MissionContext,
    context_multiplier_bp,
    contextualize,
    mission_context,
    not_configured,
    weight_of,
)
from .models import (
    CONTEXT_SOURCE,
    CONTEXT_STATUSES,
    CRITICALITIES,
    CRITICALITY_HIGH,
    CRITICALITY_LOW,
    CRITICALITY_MEDIUM,
    MISSION_CONTEXT_COMPONENT,
    MISSION_CONTEXT_MODEL_VERSION,
    MISSION_CONTEXT_SCHEMA_VERSION,
    MISSION_IMPACTS,
    MISSION_IMPACT_HIGH,
    MISSION_IMPACT_LOW,
    MISSION_IMPACT_MEDIUM,
    ROLES,
    ROLE_DEVELOPMENT,
    ROLE_MISSION_SUPPORT,
    ROLE_OPERATIONAL,
    ROLE_TEST,
    STATUS_CONFIGURED,
    STATUS_NOT_CONFIGURED,
    validate_criticality,
    validate_mission_impact,
    validate_role,
)
from .profiles import (
    DEFAULT_MISSION_PROFILES_PATH,
    MISSION_PROFILES_RELATIVE_PATH,
    AssetMissionProfile,
    MissionProfileBook,
    load_mission_profiles,
)

__all__ = [
    "AssetMissionProfile",
    "CATEGORY_WEIGHTS",
    "CONTEXT_SOURCE",
    "CONTEXT_STATUSES",
    "CRITICALITIES",
    "CRITICALITY_HIGH",
    "CRITICALITY_LOW",
    "CRITICALITY_MEDIUM",
    "ContextualizedRisk",
    "DEFAULT_MISSION_PROFILES_PATH",
    "FORMULA",
    "MAX_UPLIFT_BP",
    "MISSION_CONTEXT_COMPONENT",
    "MISSION_CONTEXT_MODEL_VERSION",
    "MISSION_CONTEXT_SCHEMA_VERSION",
    "MISSION_IMPACTS",
    "MISSION_IMPACT_HIGH",
    "MISSION_IMPACT_LOW",
    "MISSION_IMPACT_MEDIUM",
    "MISSION_PROFILES_RELATIVE_PATH",
    "MissionContext",
    "MissionProfileBook",
    "NEUTRAL_BP",
    "ROLES",
    "ROLE_DEVELOPMENT",
    "ROLE_MISSION_SUPPORT",
    "ROLE_OPERATIONAL",
    "ROLE_TEST",
    "STATUS_CONFIGURED",
    "STATUS_NOT_CONFIGURED",
    "TECHNICAL_SCORE_CAP",
    "WEIGHT_CEILING",
    "WEIGHT_FLOOR",
    "WEIGHT_SPAN",
    "context_multiplier_bp",
    "contextualize",
    "load_mission_profiles",
    "mission_context",
    "not_configured",
    "validate_criticality",
    "validate_mission_impact",
    "validate_role",
    "weight_of",
]
