connections {

    gw-b-to-gw-a {

        version = 2
        local_addrs = 192.168.100.2
        remote_addrs = 192.168.100.1

        local {
            auth = psk
            id = gw-b
        }

        remote {
            auth = psk
            id = gw-a
        }

        children {

            lan-b-to-lan-a {

                local_ts = 10.10.2.0/24
                remote_ts = 10.10.1.0/24

                esp_proposals = aes256gcm16-modp2048
                start_action = trap
            }
        }

        proposals = aes256-sha256-modp2048
    }
}
