connections {

    gw-c-to-gw-a {

        version = 2
        local_addrs = 192.168.100.3
        remote_addrs = 192.168.100.1

        local {
            auth = psk
            id = gw-c
        }

        remote {
            auth = psk
            id = gw-a
        }

        children {

            lan-c-to-lan-a {

                local_ts = 10.10.3.0/24
                remote_ts = 10.10.1.0/24

                esp_proposals = aes256gcm16-modp2048
                start_action = start
                close_action = restart
            }
        }

        # Force UDP encapsulation so EVERY SA on this gateway
        # rides the same UDP/4500 transport.
        encap = yes
        proposals = aes256-sha256-modp2048
    }
}
