import type { ReportService } from '../api/reportService'
import type { Report, ReportPreview, ReportPreviewSection, ReportRequest } from '../../types/report'
import { REPORT_TYPE_LABEL } from '../../types/report'
import { mockDataset } from './mockData'
import { invalid, latency, notFound } from './mockSupport'

/** Stages a queued report walks through, with the message shown while it runs. */
const STAGES: { status: Report['status']; progress: number; note: string }[] = [
  { status: 'queued', progress: 5, note: 'Queued' },
  { status: 'generating', progress: 40, note: 'Aggregating sessions and findings' },
  { status: 'generating', progress: 75, note: 'Rendering sections' },
  { status: 'generating', progress: 95, note: 'Writing artefacts' },
  { status: 'ready', progress: 100, note: 'Ready' },
]

export class MockReportService implements ReportService {
  private readonly reports = new Map<string, Report>(mockDataset.reports.map((item) => [item.id, item]))
  private nextId = 1
  private readonly timers = new Map<string, number>()

  async list(): Promise<Report[]> {
    return latency(
      [...this.reports.values()].sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1)),
      120,
    )
  }

  async getById(id: string): Promise<Report> {
    const report = this.reports.get(id)
    if (!report) throw notFound('Report', id)
    return latency(report, 100)
  }

  async create(request: ReportRequest): Promise<Report> {
    if (!request.name.trim()) throw invalid('A report name is required.')
    if (request.formats.length === 0) throw invalid('Select at least one output format.')
    if (request.scope.sessionIds.length === 0 && request.scope.experimentIds.length === 0) {
      throw invalid('A report must cover at least one session or experiment.')
    }

    const id = `RPT-NEW-${String(this.nextId).padStart(3, '0')}`
    this.nextId += 1
    const report: Report = {
      id,
      name: request.name.trim(),
      type: request.type,
      detailLevel: request.detailLevel,
      status: 'queued',
      scope: request.scope,
      formats: request.formats,
      createdAt: new Date().toISOString(),
      createdBy: 'you',
      sizeBytes: null,
      findingCount: mockDataset.findings.filter((finding) =>
        finding.sessionIds.some((sessionId) => request.scope.sessionIds.includes(sessionId)),
      ).length,
      sessionCount: request.scope.sessionIds.length,
      securityScore: null,
      progressPercent: 0,
    }
    this.reports.set(id, report)
    this.startGeneration(id)
    return latency(report, 120)
  }

  async remove(id: string): Promise<void> {
    if (!this.reports.has(id)) throw notFound('Report', id)
    const timer = this.timers.get(id)
    if (timer !== undefined) window.clearInterval(timer)
    this.timers.delete(id)
    this.reports.delete(id)
    return latency(undefined, 80)
  }

  async getStatus(id: string): Promise<Report['status']> {
    const report = this.reports.get(id)
    if (!report) throw notFound('Report', id)
    return latency(report.status, 40)
  }

  async getPreview(id: string): Promise<ReportPreview> {
    const report = this.reports.get(id)
    if (!report) throw notFound('Report', id)
    return latency(this.buildPreview(report), 160)
  }

  async getDownloadUrl(id: string, format: Report['formats'][number]): Promise<string> {
    const report = this.reports.get(id)
    if (!report) throw notFound('Report', id)
    if (report.status !== 'ready') throw invalid('The report is still being generated.')
    if (!report.formats.includes(format)) throw invalid(`${format.toUpperCase()} was not requested for this report.`)
    // Blob URL of a rendered placeholder: the real service returns a signed URL.
    const body = `${REPORT_TYPE_LABEL[report.type]} — ${report.name}\n\nGenerated by the IPsec Sentinel mock report service.\n`
    const url = URL.createObjectURL(new Blob([body], { type: 'text/plain' }))
    return latency(url, 60)
  }

  /** Move a queued report to ready on a timer, mirroring the backend job. */
  private startGeneration(id: string): void {
    let step = 0
    const timer = window.setInterval(() => {
      const current = this.reports.get(id)
      if (!current) {
        window.clearInterval(timer)
        this.timers.delete(id)
        return
      }
      const stage = STAGES[Math.min(step, STAGES.length - 1)]
      step += 1
      const finished = step >= STAGES.length
      this.reports.set(id, {
        ...current,
        status: stage.status,
        progressPercent: stage.progress,
        securityScore: finished ? Math.round(38 + (id.length % 17)) : current.securityScore,
        sizeBytes: finished ? 240_000 + id.length * 4_100 : current.sizeBytes,
      })
      if (finished) {
        window.clearInterval(timer)
        this.timers.delete(id)
      }
    }, 700)
    this.timers.set(id, timer)
  }

  private buildPreview(report: Report): ReportPreview {
    const findings = mockDataset.findings.filter((finding) =>
      finding.sessionIds.some((sessionId) => report.scope.sessionIds.includes(sessionId)),
    )
    const sessions = mockDataset.sessions.filter((session) => report.scope.sessionIds.includes(session.id))

    const sections: ReportPreviewSection[] = [
      {
        id: 'scope',
        title: 'Scope',
        summary: `${sessions.length} session(s) and ${report.scope.experimentIds.length} experiment(s) between ${report.scope.from.slice(0, 10)} and ${report.scope.to.slice(0, 10)}.`,
        rows: [
          { label: 'Report type', value: REPORT_TYPE_LABEL[report.type] },
          { label: 'Detail level', value: report.detailLevel },
          { label: 'Formats', value: report.formats.join(', ').toUpperCase() },
          { label: 'Requested by', value: report.createdBy },
        ],
      },
      {
        id: 'posture',
        title: 'Security posture',
        summary:
          report.securityScore === null
            ? 'Not yet assessed — the assessment runs when generation completes.'
            : `Weighted score ${report.securityScore}/100 across ${findings.length} finding(s).`,
        rows: [
          { label: 'Security score', value: report.securityScore === null ? 'Pending' : `${report.securityScore}/100` },
          { label: 'Sessions in scope', value: String(sessions.length) },
          { label: 'Findings in scope', value: String(findings.length) },
        ],
      },
      {
        id: 'findings',
        title: 'Findings',
        summary: 'Severity counts for the sessions in scope, most severe first.',
        rows: findings.slice(0, 12).map((finding) => ({
          label: finding.title,
          value: finding.severity,
          note: finding.confidence === null ? 'Confidence unknown' : `Confidence ${Math.round(finding.confidence * 100)}%`,
        })),
      },
    ]

    if (report.detailLevel !== 'summary') {
      sections.push({
        id: 'configuration',
        title: 'Negotiated configuration',
        summary: 'Protocol parameters as read from the analysed sessions.',
        rows: sessions.slice(0, 10).map((session) => ({
          label: session.label,
          value: [
            session.configuration.ikeVersion.value ?? 'Unknown',
            session.configuration.vpnMode.value ?? 'Unknown',
            session.configuration.encryption.value ?? 'Unknown',
            session.configuration.integrity.value ?? 'Unknown',
            session.configuration.dhGroup.value ?? 'Unknown',
          ].join(' · '),
        })),
      })
    }

    if (report.detailLevel === 'forensic') {
      sections.push({
        id: 'evidence',
        title: 'Evidence',
        summary: 'Evidence identifiers supporting each finding in scope.',
        rows: findings.flatMap((finding) =>
          finding.evidence.map((evidence) => ({
            label: `${finding.id} · ${evidence.field}`,
            value: evidence.rawValue ?? '—',
            note: `${evidence.source} · ${evidence.exchange}`,
          })),
        ),
      })
    }

    return {
      title: report.name,
      subtitle: REPORT_TYPE_LABEL[report.type],
      type: report.type,
      detailLevel: report.detailLevel,
      scope: report.scope,
      sections,
      generatedAt: new Date().toISOString(),
      provenance: 'Generated from mock data by the frontend report service. No backend was involved.',
    }
  }
}
